# Snapshot Configuration
# Configuration for lakehouse snapshot creation and consumption

version:
  major: 0
  minor: 1
  patch: 0

# ============================================================
# PRODUCER SETTINGS (Creating Snapshots)
# ============================================================

# Snapshot root directory - where snapshots will be SAVED/CREATED
# This is used by: lakehouse snapshot create
# Supports environment variable expansion: ${VAR_NAME:-default}
snapshot_root: "C:/Users/kylej/Cursor Projects/LAKE_ROOT"

# Auto-increment patch version on collision
auto_increment: true

# Suffix to append to provisional snapshots
provisional_suffix: "-provisional"

# ============================================================
# CONSUMER SETTINGS (Reading Snapshots)
# ============================================================

# Lake root directory - where snapshots will be READ FROM
# This is used by consuming applications/tools to read snapshot data
# Supports environment variable expansion: ${VAR_NAME:-default}
lake_root: "C:/Users/kylej/Cursor Projects/LAKE_ROOT"

# ============================================================
# EXAMPLES
# ============================================================
#
# Local development (separate locations):
#   snapshot_root: "D:/lakehouse/snapshots"    # Where you create
#   lake_root: "D:/lakehouse/snapshots/v0.9.0-provisional"  # What you read
#
# Shared network location:
#   snapshot_root: "//fileserver/lake_snapshots"
#   lake_root: "//fileserver/lake_snapshots/v1.0.0"
#
# User home directory:
#   snapshot_root: "~/lakehouse/snapshots"
#   lake_root: "~/lakehouse/snapshots/v0.9.0-provisional"
#
# Environment variables (recommended):
#   snapshot_root: "${SNAPSHOT_ROOT:-./snapshots}"
#   lake_root: "${LAKE_ROOT}"
#
# Custom version:
#   version:
#     major: 1
#     minor: 0
#     patch: 0

